dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - now --token $AUTH $(echo $(now --token $AUTH deploy)) tgclient.now.sh
  - echo "Branch = $TRAVIS_BRANCH"
